# Generated by Django 2.2.7 on 2019-11-27 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='n/a', max_length=25)),
                ('description', models.CharField(default='n/a', max_length=150)),
                ('coordinate', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Timeline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='n/a', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.TextField(default='n/a')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='wb_db_app.Event')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='timeline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='wb_db_app.Timeline'),
        ),
    ]
