# Generated by Django 2.2.7 on 2019-11-27 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wb_db_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='title',
            field=models.CharField(default='n/a', max_length=50),
        ),
    ]
