# Generated by Django 2.2.7 on 2019-11-27 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wb_db_app', '0002_note_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='timeline',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='wb_db_app.Timeline'),
        ),
        migrations.AlterField(
            model_name='note',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='wb_db_app.Event'),
        ),
    ]
