# Generated by Django 2.2.7 on 2019-12-02 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wb_db_app', '0003_auto_20191127_1953'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='event',
            new_name='timeline',
        ),
    ]
