# Generated by Django 2.2.7 on 2019-12-02 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wb_db_app', '0004_auto_20191202_0137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='timeline',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='wb_db_app.Timeline'),
        ),
    ]
